# Generated by Django 3.1.7 on 2021-02-21 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('range_from', models.IntegerField(blank=True, null=True, verbose_name='From')),
                ('range_to', models.IntegerField(blank=True, null=True, verbose_name='From')),
            ],
            options={
                'verbose_name': 'Column type',
                'verbose_name_plural': 'Column types',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('modified_date', models.DateField(auto_now=True)),
                ('separator', models.CharField(choices=[('COMMA', 'Comma (,)'), ('SEMICOLON', 'Semicolon (;)'), ('SPACE', 'space ( )')], default='COMMA', max_length=50, verbose_name='separator type')),
                ('quote', models.CharField(choices=[('QUOTE', "Quote (')"), ('DOUBLE QUOTE', 'Double quote (")')], default='QUOTE', max_length=50, verbose_name='Quote type')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemas',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Name')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='generator.schema', verbose_name='Schema')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.columntype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
            },
        ),
    ]
