# Generated by Django 3.1.7 on 2021-02-26 18:44

from django.db import migrations, models
import django.db.models.deletion
import utils.upload_dataset


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(verbose_name='Rows')),
                ('created_date', models.DateField(auto_now=True)),
                ('ready', models.BooleanField(default=False, verbose_name='Ready')),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.upload_dataset.upload_instance, verbose_name='File')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='builder.schema', verbose_name='Dataset')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
            },
        ),
    ]
