# Generated by Django 3.1.7 on 2021-02-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columntype',
            name='range_from',
        ),
        migrations.RemoveField(
            model_name='columntype',
            name='range_to',
        ),
        migrations.AddField(
            model_name='column',
            name='range_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='column',
            name='range_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AddField(
            model_name='columntype',
            name='is_range',
            field=models.BooleanField(default=False, verbose_name='Range?'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='quote',
            field=models.CharField(choices=[("Quote (')", 'QUOTE'), ('Double quote (")', 'DOUBLE QUOTE')], default='QUOTE', max_length=50, verbose_name='Quote type'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='separator',
            field=models.CharField(choices=[('Comma (,)', 'COMMA'), ('Semicolon (;)', 'SEMICOLON'), ('Space ( )', 'SPACE')], default='COMMA', max_length=50, verbose_name='separator type'),
        ),
    ]
