# Generated by Django 3.1.7 on 2021-02-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
        ('generator', '0002_auto_20210226_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='builder.schema', verbose_name='Schema'),
        ),
    ]
